/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function AboutUs(props) {
  return (
    <section className="flex-col overflow-hidden relative flex min-[706px] w-full items-center px-5 py-12 max-md:max-w-full">
      <h1>
        <span className="text-zinc-50 text-7xl leading-[118px]" style={{ textShadow: '-1px 0 black, 0 1px black, 1px 0 black, 0 -1px black' }}>
          ABOUT US
        </span>
      </h1>
      <div className="relative w-full max-w-[1125px] mt20 mb-20 pr-px max-md:max-w-full max-md:my-10">
        <div className="gap-5 flex max-md:flex-col max-mditems-stretch max-md:gap-0">
          <div className="flex flex-col items-stretch w-[58%] max-md:w-full max-md:0">
            <div className="relative flex flex-col items-stretch mt-7 max-md:max-w-full max-md:mt-10">
              <p className="text-white text-xl leading-7 mt-20 max-md:max-w-full max-md:mt-10">
                Established in 1992, Samurai Ink Studio has become a renowned hub for tattoo and piercing craftsmanship. Our highly skilled team of artists is devoted to creating a secure, hygienic, and inviting atmosphere for our valued clients. Drawing from innovation and driven by the desire to exceed artistic limits, we aim to deliver personalized body art that captures your individuality and showcases your distinct style.
              </p>
            </div>
          </div>

          <div className="flex flex-col items-stretch w-[42%] ml-5 max-md:w-full max-md:ml-0">
            <img loading="lazy" srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/4dfa2bfc-9c81-48e4-852b-c55cb160e508?placeholderIfAbsent=true" className="aspect-[1.1] object-contain object-center w-full overflow-hidden grow max-md:max-w-full max-md:mt-9" />
          </div>
        </div>
      </div>
    </section>
  );
}

export default AboutUs;
