/**
 * This code was generated by Builder.io.
 */
import React from "react";
import CustomerComponent from "./CustomerComponent";

export const Footer = () => {
  return (
    <div className="w-full bg-black -mt-px pl-3 pr-20 pb-2 max-md:max-w-full max-md:pr-5">
      <header>
        <nav className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
          <div className="flex flex-col items-stretch w-6/12 max-md:w-full max-md:ml-0">
            <div className="flex flex-col max-md:max-w-full max-md:mt-5">
              <div className="flex w-[457px] max-w-full flex-col items-stretch">
                <img
                  loading="lazy"
                  srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/6efc6d91-8ede-44d5-a9c9-c2af88f228ea?placeholderIfAbsent=true"
                  alt="Logo"
                  className="aspect-[1.13] object-contain object-center w-full overflow-x-hidden overflow-y-hidden max-md:max-w-full"
                />
                <div className="max-w-[409px] self-center text-xl leading-7 text-white mt-6">
                  <span className="text-red-600">Samurai</span>{" "}
                  <span className="text-white" />{" "}
                  <span className="text-neutral-50">I</span>{" "}
                  <span className="text-white">nk </span>{" "}
                  <span className="text-neutral-50">S</span>{" "}
                  <span className="text-white">tudio</span>
                </div>
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/02f36a7a-9620-4af3-93e6-fe60aa1f7e60?apiKey=f5b9441429c64a0aaa7125b729b9e51b&"
                  alt="Image"
                  className="aspect-[3.54] object-contain object-center w-[184px] max-w-full self-center overflow-x-hidden overflow-y-hidden mt-4"
                />
              </div>
              <div className="self-stretch text-xl leading-7 font-bold text-white mt-5 max-md:max-w-full">
                Copyright 2023
              </div>
            </div>
          </div>
          <div className="flex flex-col items-stretch w-6/12 ml-5 max-md:w-full max-md:ml-0">
            <div className="flex flex-col items-stretch my-auto max-md:max-w-full max-md:mt-10">
              <div className="max-md:max-w-full">
                <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
                  <div className="flex flex-col items-stretch w-6/12 max-md:w-full max-md:ml-0">
                    <div className="flex flex-col items-stretch max-md:mt-10">
                      <div className="text-xl leading-7 text-zinc-50">
                        Contact Us
                      </div>
                      <div className="text-xl leading-7 text-white mt-28 max-md:mt-10">
                        <br /> <br />
                        <span>Kabukicho: +81 90-1234-5678</span> <br /> <br />{" "}
                        <br />
                        <span>123 Kabukicho,</span> <br />
                        <span>Shinjuku-ku, </span> <br />
                        <span>Tokyo,</span> <br />
                        <span>Japan</span> <br /> <br />
                      </div>
                    </div>
                  </div>

                 <CustomerComponent />

                </div>
              </div>
            </div>
          </div>
        </nav>
      </header>
    </div>
  );
};

export default Footer;
