/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function Gallery(props) {
  return (
    <section className="bg-zinc-800 flex w-full flex-col items-center px-5 py-12 max-md:max-w-full">
      <h1>
        <span className="text-zinc-50 text-7xl leading-[118px]" style={{ textShadow: '-1px 0 black, 0 1px black, 1px 0 black, 0 -1px black' }}>
          Gallery
        </span>
      </h1>
      <div className="self-stretch mt-12 max-md:max-w-full max-md:mt-10">
        <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
          <figure className="flex flex-col items-stretch w-3/12 max-md:w-full max-md:ml-0">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/cf3b7529-f007-49de-bed0-9c44d9a14539?placeholderIfAbsent=true"
              className="aspect-[0.9] object-contain object-center w-full overflow-hidden grow max-md:mt-5"
              alt="Image 1"
            />
          </figure>
          <figure className="flex flex-col items-stretch w-3/12 ml-5 max-md:w-full max-md:ml-0">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/16949bd3-83c0-434e-918d-980a36c36528?placeholderIfAbsent=true"
              className="aspect-[0.9] object-contain object-center w-full overflow-hidden grow max-md:mt-5"
              alt="Image 2"
            />
          </figure>
          <figure className="flex flex-col items-stretch w-3/12 ml-5 max-md:w-full max-md:ml-0">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/18f2dbfe-69df-4ccf-b544-780ef580a42b?placeholderIfAbsent=true"
              className="aspect-[0.9] object-contain object-center w-full overflow-hidden grow max-md:mt-5"
              alt="Image 3"
            />
          </figure>
          <figure className="flex flex-col items-stretch w-3/12 ml-5 max-md:w-full max-md:ml-0">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/05d486a9-6647-476e-905f-d30e48c9adc2?placeholderIfAbsent=true"
              className="aspect-[0.9] object-contain object-center w-full overflow-hidden grow max-md:mt-5"
              alt="Image 4"
            />
          </figure>
        </div>
      </div>
      <div className="self-stretch mt-5 max-md:max-w-full">
        <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
          <figure className="flex flex-col items-stretch w-3/12 max-md:w-full max-md:ml-0">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/e3f86b7f-7c45-4a9f-b4bc-d2957e9ec755?placeholderIfAbsent=true"
              className="aspect-[0.9] object-contain object-center w-full overflow-hidden grow max-md:mt-5"
              alt="Image 5"
            />
          </figure>
          <figure className="flex flex-col items-stretch w-3/12 ml-5 max-md:w-full max-md:ml-0">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/4ee9286d-765f-4ca7-9619-53f9dad368dd?placeholderIfAbsent=true"
              className="aspect-[0.9] object-contain object-center w-full overflow-hidden grow max-md:mt-5"
              alt="Image 6"
            />
          </figure>
          <figure className="flex flex-col items-stretch w-3/12 ml-5 max-md:w-full max-md:ml-0">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/41bb3dfd-77f2-4032-a98e-21c4ccf14a48?placeholderIfAbsent=true"
              className="aspect-[0.9] object-contain object-center w-full overflow-hidden grow max-md:mt-5"
              alt="Image 7"
            />
          </figure>
          <figure className="flex flex-col items-stretch w-3/12 ml-5 max-md:w-full max-md:ml-0">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/de8c9288-5f7a-4403-82ad-30c60402a66f?placeholderIfAbsent=true"
              className="aspect-[0.9] object-contain object-center w-full overflow-hidden grow max-md:mt-5"
              alt="Image 8"
            />
          </figure>
        </div>
      </div>
    </section>
  );
}

export default Gallery;
