/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function GiftVouchersComponent(props) {
  return (
    <div className="flex-col overflow-hidden relative flex min-h-[509px] items-center px-5">
      <div
        className="absolute z-[-2] h-full w-full inset-0"
        style={{ backgroundColor: "white" }}
      ></div>
      <img
        loading="lazy"
        srcSet="https://cdn.builder.io/api/v1/image/assets%2Ff5b9441429c64a0aaa7125b729b9e51b%2Fce65438cbb6948c6b74448969d25db7c"
        className="absolute z-[-1] h-full w-full object-cover object-center inset-0 opacity-50"
      />
      <div className="relative w-full max-w-[1116px] mt-12 mb-6 max-md:max-w-full max-md:mt-10">
        <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
          <div className="flex flex-col items-stretch w-6/12 max-md:w-full max-md:ml-0">
            <div className="flex-col text-white text-center text-3xl leading-10 relative max-w-[367px] overflow-hidden min-h-[435px] grow items-center pt-44 pb-40 px-5 max-md:max-w-full max-md:mt-8 max-md:py-10">
              <img loading="lazy" srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/16837847-7f6d-4e76-b8d1-72d9529d453b?placeholderIfAbsent=true" className="absolute z-[-1] h-full w-full object-cover object-center inset-0" />
              GIFT VOUCHERS
            </div>
          </div>
          <div className="flex flex-col items-stretch w-6/12 ml-5 max-md:w-full max-md:ml-0">
            <div className="relative flex grow flex-col items-stretch max-md:max-w-full max-md:mt-8">
              <div className="pr-px max-md:max-w-full">
                <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
                  <div className="flex flex-col items-stretch w-6/12 max-md:w-full max-md:ml-0">
                    <div className="flex-col overflow-hidden relative flex aspect-[1.2380952380952381] grow items-stretch pl-12 pr-12 pt-12 pb-10 max-md:mt-5 max-md:px-5">
                      <img loading="lazy" srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/49cb3e2e-7216-4d35-a248-f77e884593d6?placeholderIfAbsent=true" className="absolute z-[-1] h-full w-full object-cover object-center inset-0" />
                      <div className="relative text-white text-center text-lg leading-7 mt-10">TATTOOS</div>
                      <div className="relative text-white text-center text-xs leading-4 mt-16 max-md:mt-">HOURLY AND DAILY</div>
                    </div>
                  </div>
                  <div className="flex flex-col items-stretch w-6/12 ml-5 max-md:w-full max-md:ml-0">
                    <div className="flex-col overflow-hidden relative flex aspect-[1.2380952380952381] grow items-stretch pt-12 pb-10 px-8 max-md:mt-5 max-md:px-5">
                      <img loading="lazy" srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/c7f3e421-5626-4261-8e90-bc5a5439bfdb?placeholderIfAbsent=true" className="absolute z-[-1] h-full w-full object-cover object-center inset-0" />
                      <div className="relative text-white text-center text-lg leading-7 whitespace-nowrap mt-10">AFTERCARE</div>
                      <div className="relative text-white text-center text-xs leading-4 mt-16 max-md:mt-10">Aftercare</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="mt-5 max-md:max-w-full">
              <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
                <div className="flex flex-col items-stretch w-6/ max-md:w-full max-md:ml-0">
                  <div className="flex-col text-white text-center text-lg leading-7 relative overflow-hidden aspect-[1.2380952380952381] grow items-center pt-16 pb-20 px-5 max-md:mt-5">
                    <img loading="lazy" srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/ae885d56-21cd-41cc-b5ea-2bd9f239bee5?placeholderIfAbsent=true" className="absolute z-[-1] h-full w-full object-cover object-center inset-0" />
                    LASER TATTOO REMOVAL <br />
                  </div>
                </div>
                <div className="flex flex-col items-stretch w-6/12 ml-5 max-md:w-full max-md:ml-0">
                  <div className="flex-col overflow-hidden relative flex aspect-[1.2380952380952381] grow items-stretch pl-4 pr-2.5 pt-12 pb-10 max-md:mt-5 max-md:px-5">
                    <img loading="lazy" srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/43f515de-9b55-458e-9827-908077705eb2?placeholderIfAbsent=true" className="absolute z-[-1] h-full w-full object-cover object-center inset-0" />
                    <div className="relative text-white text-center text-lg leading-7 mt-10">MERCHANDISE</div>
                    <div className="relative text-white text-center text-xs leading-4 mt-16 max-md:mt-10">APPAREL</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default GiftVouchersComponent;
