/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function Services(props) {
  return (
    <section className="bg-black flex w-full flex-col items-center px-5 py-12 max-md:max-w-full">
      <div className="w-full max-w-[1107px] mt-11 mb-16 max-md:max-w-full max-md:my-10">
        <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
          <div className="flex flex-col items-stretch w-[43%] max-md:w-full max-md:ml-0">
            <img
              loading="lazy"
              srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/1e7cac3f-0a47-4bed-a905-d978354e2d8e?placeholderIfAbsent=true"
              className="aspect-[0.88] object-contain object-center w-full overflow-hidden grow max-md:max-w-full max-md:mt-10"
              alt="Tattoo Studio"
            />
          </div>
          <div className="flex flex-col items-stretch w-[57%] ml-5 max-md:w-full max-md:ml-0">
            <div className="flex flex-col items-stretch mt-3 max-md:max-w-full max-md:mt-10">
              <p className="text-white text-lg leading-7 max-md:max-w-full">
                We honor the tradition of body as canvas, guiding you to create a unique masterpiece. Immerse yourself in our realm of artistry, where skilled samurais transform your vision into stunning tattoos or intricate piercings. With a dedication to craftsmanship and boundless creativity, we bring forth the essence of your story.
                <br />
                <br />
                Discover the vibrant world of body art, encounter our eclectic artists, and ignite your imagination for your next indelible mark. Join our esteemed society and embark on a profound journey of self-expression and personal awakening at Samurai Ink Studios.
                <br />
                <br />
              </p>
              <div className="flex w-[467px] max-w-full justify-between gap-5 ml-7 mt-14 self-start max-md:flex-wrap max-md:mt-10">
                <a href="#" className="justify-center text-white text-base leading-6 whitespace-nowrap bg-black grow px-5 py-5 border-[5px] border-solid border-white">
                  SERVICES
                </a>
                <a href="#" className="justify-center text-white text-base leading-6 whitespace-nowrap bg-black grow items-stretch mt-1.5 px-5 py-5 border-[5px] border-solid border-white max-md:pr-0.5">
                  OUR TEAM
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

export default Services;
